const API='https://data.ny.gov/resource/d6yy-54nr.json?$limit=5000&$order=draw_date%20DESC';
const ERA_START=new Date('2015-10-07T00:00:00');
let draws=[];
const $=id=>document.getElementById(id);

function parseDraw(r){const nums=String(r.winning_numbers||'').trim().split(/\s+/).map(Number).filter(Number.isFinite);if(nums.length<6)return null;return{date:new Date(r.draw_date),white:nums.slice(0,5),pb:nums[5]}}
function freq(values,max){const a=Array(max+1).fill(0);values.forEach(v=>a[v]++);return a}
function rank(f,asc=false){return [...f.keys()].slice(1).sort((a,b)=>asc?f[a]-f[b]:f[b]-f[a])}
function weightedPick(pool,weight){let sum=pool.reduce((s,n)=>s+Math.max(.001,weight(n)),0),r=Math.random()*sum;for(const n of pool){r-=Math.max(.001,weight(n));if(r<=0)return n}return pool.at(-1)}
function latestIndex(num,isPb=false){for(let i=0;i<draws.length;i++){if(isPb?draws[i].pb===num:draws[i].white.includes(num))return i}return draws.length}
function stats(){const whites=draws.flatMap(d=>d.white),pbs=draws.map(d=>d.pb),wf=freq(whites,69),pf=freq(pbs,26);const avg=draws.reduce((s,d)=>s+d.white.reduce((a,b)=>a+b,0),0)/draws.length;const patterns={};draws.forEach(d=>{const odd=d.white.filter(n=>n%2).length;patterns[`${odd}/${5-odd}`]=(patterns[`${odd}/${5-odd}`]||0)+1});return{wf,pf,avg,pattern:Object.entries(patterns).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'}}
function scoreWeight(n,strategy,s,isPb=false){const f=isPb?s.pf:s.wf;const max=Math.max(...f);const min=Math.min(...f.slice(1));const hot=(f[n]-min+1)/(max-min+1);const overdue=(latestIndex(n,isPb)+1)/(draws.length+1);if(strategy==='hot')return .15+hot*2;if(strategy==='cold')return .15+(1-hot)*2;if(strategy==='overdue')return .15+overdue*3;if(strategy==='random')return 1;if(strategy==='blend')return .25+(n%2?hot:1-hot)*1.7+overdue*.4;return .35+hot*.85+overdue*.35}
function generateLine(strategy,s){let best=null,bestPenalty=Infinity;for(let attempt=0;attempt<120;attempt++){const pool=Array.from({length:69},(_,i)=>i+1),white=[];while(white.length<5){const n=weightedPick(pool,x=>scoreWeight(x,strategy,s,false));white.push(n);pool.splice(pool.indexOf(n),1)}white.sort((a,b)=>a-b);const pb=weightedPick(Array.from({length:26},(_,i)=>i+1),x=>scoreWeight(x,strategy,s,true));if(strategy==='random')return{white,pb};const sum=white.reduce((a,b)=>a+b,0),odd=white.filter(n=>n%2).length,spread=white[4]-white[0];const penalty=Math.abs(sum-s.avg)*.8+Math.abs(odd-2.5)*7+(spread<30?(30-spread)*.5:0);if(penalty<bestPenalty){bestPenalty=penalty;best={white,pb}}}return best}
function renderStats(s){$('drawCount').textContent=draws.length.toLocaleString();$('avgSum').textContent=s.avg.toFixed(1);$('oddEven').textContent=s.pattern.replace('/',' odd / ')+' even';$('latestDraw').textContent=draws[0].date.toLocaleDateString();$('hotBalls').innerHTML=rank(s.wf).slice(0,8).map(n=>`<span>${n}</span>`).join('');$('hotPowerballs').innerHTML=rank(s.pf).slice(0,6).map(n=>`<span>${n}</span>`).join('')}
function renderPicks(lines){$('picks').className='picks';$('picks').innerHTML=lines.map((l,i)=>`<div class="pick-row"><span class="pick-index">${String(i+1).padStart(2,'0')}</span>${l.white.map(n=>`<span class="ball">${n}</span>`).join('')}<span class="ball pb">${l.pb}</span></div>`).join('');$('copyBtn').disabled=false;$('copyBtn').dataset.text=lines.map((l,i)=>`${i+1}. ${l.white.join(' - ')} | PB ${l.pb}`).join('\n')}
async function load(){try{const res=await fetch(API);if(!res.ok)throw new Error(`HTTP ${res.status}`);const raw=await res.json();draws=raw.map(parseDraw).filter(Boolean).filter(d=>d.date>=ERA_START).sort((a,b)=>b.date-a.date);if(!draws.length)throw new Error('No current-era draws returned');const s=stats();renderStats(s);window.powerballStats=s;$('statusDot').classList.add('ready');$('statusText').textContent='Historical data ready';$('statusMeta').textContent=`${draws.length.toLocaleString()} draws · Oct 7, 2015 to ${draws[0].date.toLocaleDateString()}`;$('generateBtn').disabled=false}catch(e){$('statusDot').classList.add('error');$('statusText').textContent='Historical data unavailable';$('statusMeta').textContent='Try again later · '+e.message;$('picks').textContent='The public data feed could not be loaded.'}}
$('generateBtn').addEventListener('click',()=>{const strategy=$('strategy').value,count=Number($('count').value),seen=new Set(),lines=[];while(lines.length<count){const line=generateLine(strategy,window.powerballStats);const key=line.white.join(',')+'|'+line.pb;if(!seen.has(key)){seen.add(key);lines.push(line)}}renderPicks(lines)});
$('copyBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText($('copyBtn').dataset.text||'');const old=$('copyBtn').textContent;$('copyBtn').textContent='Copied';setTimeout(()=>$('copyBtn').textContent=old,1200)});
load();